version: "3"
services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./docker_data/postgres/:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: on-failure

  # ffmpeg:
  #   container_name: ffmpeg
  #   image: linuxserver/ffmpeg:latest
  #   volumes:
  #     - ./docker_data/ffmpeg:/config
  #   restart: on-failure
